# Generated by Django 2.0 on 2020-01-08 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('acronym', models.CharField(max_length=10, verbose_name='Acronym')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('headquarters', models.CharField(help_text='The direction of the headquarters', max_length=200, verbose_name='Headquarters')),
                ('image', models.CharField(blank=True, help_text='Must be a link', max_length=500, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Image')),
                ('president', models.CharField(blank=True, help_text='You must do a primary presidential voting if you want select a new president', max_length=151, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='voting',
            name='tipe',
            field=models.TextField(choices=[('PP', 'Presidential primaries'), ('SP', 'Senate primaries'), ('S', 'Senate'), ('P', 'Presidential')], default='O', verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.TextField(help_text='You must put a valid username'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterUniqueTogether(
            name='politicalparty',
            unique_together={('name', 'acronym')},
        ),
        migrations.AddField(
            model_name='voting',
            name='political_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.PoliticalParty'),
        ),
    ]
