# Generated by Django 2.0 on 2020-01-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20200108_1609'),
        ('voting', '0015_merge_20200110_2107'),
    ]

    operations = [
    ]
